vk:
  groupId: 123 # Id группы ВК 
  accessToken: "token" # Токен группы ВК

rcon:
  host: "localhost" # Адрес RCON
  port: 19132 # Порт RCON
  password: "password" # Пароль RCON

commands:
  # Символ перед командой для отправки комманды. Например '/'.
  # Оставьте пустым если не требуется.
  prefix: '/'

  # Быстрые команды
  # (Отображаются при вводе "Начать", "Rcon")
  fast-commands: ["ver:", "status", "stop"]

  # Заблокированные команды
  blocked-commands: ["stop"]
