# Доступные языки: eng (English), rus (Русский)
language: "rus"

# Настройки VK
vk:
  groupId: 123 # Id группы ВК 
  accessToken: "token" # Токен группы ВК

# Настройки RCON
rcon:
  host: "localhost" # Адрес RCON
  port: 19132 # Порт RCON
  password: "password" # Пароль RCON

# Настройки команд
commands:
  # Символ перед командой для отправки комманды. Например '/'.
  # Оставьте пустым если не требуется.
  prefix: '/'

  # Быстрые команды
  # (Отображаются при вводе "Начать", "Rcon")
  fast-commands: ["ver", "status", "stop"]

  # Заблокированные команды
  blocked-commands: ["stop"]
